TRIGGER_PIN_LEFT = 18    # physical pin 12
ECHO_PIN_LEFT = 24       # physical pin 18
TRIGGER_PIN_FRONT = 17   # physical pin 11
ECHO_PIN_FRONT = 27      # physical pin 13
TRIGGER_PIN_RIGHT = 5    # physical pin 29
ECHO_PIN_RIGHT = 6       # physical pin 31
BUZZER_PIN = 23          # physical pin 16
REMOTE_PIN = 26
LED_PIN = 25
